/*
    nilt - Numerical Inverse Laplace Transform library (C++14, header-only)

    Three algorithms are provided, each suited to different use cases:

      Stehfest - Real-valued F(s) only.  Very fast (constexpr coefficients).
                 Best for smooth, monotonically decaying transforms.
      Talbot   - Complex F(s).  Moderate cost (constexpr contour table).
                 Robust for oscillatory and steep transforms.
      DeHoog   - Complex F(s).  Highest cost but most accurate for difficult
                 transforms (discontinuities, long-time behaviour).

    Usage:
        #include <nilt.hpp>

        // Scalar inversion
        double f1 = nilt::invert(nilt::Talbot{}, [](auto s){ return 1.0/(s+1.0); }, 1.0);

        // Vector inversion (algorithm is constructed once, reused for all t)
        std::vector<double> t = {0.1, 0.5, 1.0, 2.0, 5.0};
        auto f = nilt::invert(nilt::Talbot{}, [](auto s){ return 1.0/(s+1.0); }, t);

        // With custom parameters
        nilt::Stehfest algo;
        algo.N = 12;
        double f2 = nilt::invert(algo, my_func, 1.0);
*/
#ifndef NILT_HEADER
#define NILT_HEADER

#include <cmath>
#include <complex>
#include <stdexcept>
#include <vector>

#include "stehfest.hpp"
#include "talbot.hpp"
#include "dehoog.hpp"

// Version macros (NILT_VERSION_MAJOR/MINOR/PATCH/STRING).  Generated by CMake
// into ${build}/generated/nilt/version.hpp and installed alongside the other
// nilt headers.  Included last so a stripped-down build without the generated
// tree still yields a clear "file not found" pointing at the CMake step.
#include <nilt/version.hpp>

namespace nilt {

/// Invert the Laplace transform Fs at a single time t.
template<typename Algo, typename F>
double invert(const Algo& algo, F&& Fs, double t)
{
    return algo(std::forward<F>(Fs), t);
}

/// Invert the Laplace transform Fs at multiple times.
/// The algorithm instance is reused across all evaluations, so any
/// precomputed tables (Stehfest coefficients, Talbot contour) are cached.
template<typename Algo, typename F>
std::vector<double> invert(const Algo& algo, F&& Fs, const std::vector<double>& t_values)
{
    std::vector<double> results(t_values.size());
    for (size_t i = 0; i < t_values.size(); ++i)
        results[i] = algo(Fs, t_values[i]);
    return results;
}

} // namespace nilt

#endif // NILT_HEADER
