name: Draft JOSS PDF

on: 
  push:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml

permissions:
  contents: read

jobs:
  paper:
    runs-on: ubuntu-latest
    name: 📄 paper draft
    
    permissions:
        contents: write

    steps:
      - name: 🛒 checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 📄 build draft pdf
        uses: openjournals/openjournals-draft-action@85a18372e48f551d8af9ddb7a747de685fbbb01c # v1.0
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: ⬆️ upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1

        with:
          name: paper
          path: paper/paper.pdf
