name: Release

permissions:
  contents: read

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cpp-tests:
    name: 🖥️ C++ tests
    uses: ./.github/workflows/cpp-tests.yml
    permissions:
      contents: read

  python-tests:
    name: 🐍 Python tests
    uses: ./.github/workflows/python-tests.yml
    permissions:
      contents: read

  release:
    name: 🚀 release
    needs: [cpp-tests, python-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest

    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write

    steps:
      - name: 🛒 checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref_name }}

      - name: 🔄 force branch to workflow sha
        run: git reset --hard ${{ github.sha }}

      - name: 🚀 python semantic release
        uses: python-semantic-release/python-semantic-release@350c48fcb3ffcdfd2e0a235206bc2ecea6b69df0 # v10.5.3
        id: release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
